#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Mar 13 11:45:33 CET 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/tools/Xilinx/2025.1/data"

# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip -prj EM_REC_Delay_Duty_ModeTb_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_21 -L smartconnect_v1_0 -L xilinx_vip -prj EM_REC_Delay_Duty_ModeTb_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj EM_REC_Delay_Duty_ModeTb_vhdl.prj"
xvhdl --incr --relax -prj EM_REC_Delay_Duty_ModeTb_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
