#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 13 11:45:36 CET 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim EM_REC_Delay_Duty_ModeTb_behav -key {Behavioral:sim_1:Functional:EM_REC_Delay_Duty_ModeTb} -tclbatch EM_REC_Delay_Duty_ModeTb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim EM_REC_Delay_Duty_ModeTb_behav -key {Behavioral:sim_1:Functional:EM_REC_Delay_Duty_ModeTb} -tclbatch EM_REC_Delay_Duty_ModeTb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

