#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Script generated by Vivado on Wed Mar 18 15:57:23 CET 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname microblaze_v11_0_15 -libname xil_defaultlib -libname lmb_v10_v3_0_15 -libname lmb_bram_if_cntlr_v4_0_26 -libname blk_mem_gen_v8_4_11 -libname generic_baseblocks_v2_1_2 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_35 -libname fifo_generator_v13_2_13 -libname axi_data_fifo_v2_1_35 -libname axi_crossbar_v2_1_37 -libname axi_lite_ipif_v3_0_4 -libname axi_intc_v4_1_21 -libname mdm_v3_2_28 -libname proc_sys_reset_v5_0_17 -libname axi_uartlite_v2_0_39 -libname interrupt_control_v3_1_5 -libname axi_gpio_v2_0_37 -libname xlconstant_v1_1_10 -libname xlconcat_v2_1_7 -libname axi_datamover_v5_1_37 -libname axi_sg_v4_1_21 -libname axi_dma_v7_1_36 -libname axi_bram_ctrl_v4_1_13 -libname axis_infrastructure_v1_1_1 -libname axis_register_slice_v1_1_35 -libname axis_subset_converter_v1_1_35 -libname smartconnect_v1_0 -libname axi_vip_v1_1_21 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm microblaze_v11_0_15 xil_defaultlib lmb_v10_v3_0_15 lmb_bram_if_cntlr_v4_0_26 blk_mem_gen_v8_4_11 generic_baseblocks_v2_1_2 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_35 fifo_generator_v13_2_13 axi_data_fifo_v2_1_35 axi_crossbar_v2_1_37 axi_lite_ipif_v3_0_4 axi_intc_v4_1_21 mdm_v3_2_28 proc_sys_reset_v5_0_17 axi_uartlite_v2_0_39 interrupt_control_v3_1_5 axi_gpio_v2_0_37 xlconstant_v1_1_10 xlconcat_v2_1_7 axi_datamover_v5_1_37 axi_sg_v4_1_21 axi_dma_v7_1_36 axi_bram_ctrl_v4_1_13 axis_infrastructure_v1_1_1 axis_register_slice_v1_1_35 axis_subset_converter_v1_1_35 smartconnect_v1_0 axi_vip_v1_1_21)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2025.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/tools/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/tools/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_15 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/75f6/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_microblaze_0_0_2/sim/design_1_microblaze_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_15 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/b1c4/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_dlmb_v10_0_2/sim/design_1_dlmb_v10_0.vhd" \
  "../../../bd/design_1/ip/design_1_ilmb_v10_0_2/sim/design_1_ilmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_26 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/0e64/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0_2/sim/design_1_dlmb_bram_if_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0_2/sim/design_1_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_11 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a32c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_lmb_bram_0_2/sim/design_1_lmb_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_2 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_35 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_13 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/dc46/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_13 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/dc46/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_13 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/dc46/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_35 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/4846/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_37 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a1a7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_microblaze_0_axi_periph_imp_xbar_0/sim/design_1_microblaze_0_axi_periph_imp_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_intc_v4_1_21 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/9eb6/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_microblaze_0_axi_intc_0_2/sim/design_1_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mdm_v3_2_28 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/00dd/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_mdm_1_0_2/sim/design_1_mdm_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_17 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_Clk_100M_0_1/sim/design_1_rst_Clk_100M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_uartlite_v2_0_39 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/eab1/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_uartlite_0_0/sim/design_1_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_37 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/0271/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_1_0/sim/design_1_axi_gpio_1_0.vhd" \
  "../../../bd/design_1/ip/design_1_SPI_slave_0_0/sim/design_1_SPI_slave_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_10 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
  "../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_gpio_2_0/sim/design_1_axi_gpio_2_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_irq_spi_0/sim/design_1_axi_gpio_irq_spi_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ClkTest_0_0/sim/design_1_ClkTest_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_receive_signal_0_0/sim/design_1_receive_signal_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_3_0/sim/design_1_axi_gpio_3_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_4_0/sim/design_1_axi_gpio_4_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_7 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/9c1a/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_conv_funs_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_proc_common_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_ipif_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_family_support.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_family.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_soft_reset.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_pselect_f.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_address_decoder.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_slave_attachment.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_interrupt_control.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_xadc_wiz_0_0_axi_lite_ipif.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_drp_arbiter.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_drp_to_axi_stream.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_xadc_core_drp.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0_axi_xadc.vhd" \
  "../../../bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_37 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/d44a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_sg_v4_1_21 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/b193/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_dma_v7_1_36 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/cb19/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_dma_0_0/sim/design_1_axi_dma_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_bram_ctrl_v4_1_13 -V93 $xmvhdl_opts \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/2f03/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_register_slice_v1_1_35 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/be12/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdata_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tuser_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tstrb_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tkeep_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tid_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tdest_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/tlast_design_1_axis_subset_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_subset_converter_v1_1_35 $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/26da/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/hdl/top_design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axis_subset_converter_0_0/sim/design_1_axis_subset_converter_0_0.v" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_arsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_rsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_awsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_wsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/sim/bd_afc3_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/sim/bd_afc3_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/sim/bd_afc3_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/sim/bd_afc3_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/sim/bd_afc3_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/sim/bd_afc3_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/sim/bd_afc3_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/sim/bd_afc3_sawn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/sim/bd_afc3_swn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/sim/bd_afc3_sbn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/sim/bd_afc3_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/sim/bd_afc3_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/sim/bd_afc3_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/sim/bd_afc3_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/sim/bd_afc3_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/sim/bd_afc3_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/sim/bd_afc3_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_21 $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_gpio_5_0/sim/design_1_axi_gpio_5_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_6_0/sim/design_1_axi_gpio_6_0.vhd" \
  "../../../bd/design_1/ip/design_1_Btn_led_0_0/sim/design_1_Btn_led_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_7_0/sim/design_1_axi_gpio_7_0.vhd" \
  "../../../bd/design_1/ip/design_1_EM_REC_Delay_Duty_Mo_0_0/sim/design_1_EM_REC_Delay_Duty_Mo_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_EM_REC_Delay_Duty_Mo_1_0/sim/design_1_EM_REC_Delay_Duty_Mo_1_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_8_0/sim/design_1_axi_gpio_8_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_9_0/sim/design_1_axi_gpio_9_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_10_0/sim/design_1_axi_gpio_10_0.vhd" \
  "../../../bd/design_1/ip/design_1_EM_REC_Delay_Duty_Mo_2_0/sim/design_1_EM_REC_Delay_Duty_Mo_2_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_11_0/sim/design_1_axi_gpio_11_0.vhd" \
  "../../../bd/design_1/ip/design_1_SW_follow_input_Sign_0_0/sim/design_1_SW_follow_input_Sign_0_0.vhd" \
  "../../../bd/design_1/ip/design_1_SW_follow_input_Sign_1_0/sim/design_1_SW_follow_input_Sign_1_0.vhd" \
  "../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a9be" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../AH_CMOD_35t.gen/sources_1/bd/design_1/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../tools/Xilinx/2025.1/data/rsb/busdef" +incdir+"/tools/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_microblaze_0_axi_periph_imp_tier2_xbar_0_0/sim/design_1_microblaze_0_axi_periph_imp_tier2_xbar_0_0.v" \
  "../../../bd/design_1/ip/design_1_microblaze_0_axi_periph_imp_tier2_xbar_1_0/sim/design_1_microblaze_0_axi_periph_imp_tier2_xbar_1_0.v" \
  "../../../bd/design_1/ip/design_1_microblaze_0_axi_periph_imp_tier2_xbar_2_0/sim/design_1_microblaze_0_axi_periph_imp_tier2_xbar_2_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/yousef/Vivado_workspace/AH_CMOD_35t/AH_CMOD_35t.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
