#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIDMA_NUM_INSTANCES 1

/* Definitions for peripheral AXI_DMA_0 */
#define XPAR_AXI_DMA_0_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_AXI_DMA_0_BASEADDR 0x41e00000
#define XPAR_AXI_DMA_0_HIGHADDR 0x41e0ffff
#define XPAR_AXI_DMA_0_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S 0x0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S_DRE 0x0
#define XPAR_AXI_DMA_0_MM2S_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_0_INCLUDE_S2MM 0x1
#define XPAR_AXI_DMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_AXI_DMA_0_S2MM_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_0_NUM_MM2S_CHANNELS 0x1
#define XPAR_AXI_DMA_0_NUM_S2MM_CHANNELS 0x1
#define XPAR_AXI_DMA_0_MM2S_BURST_SIZE 0x10
#define XPAR_AXI_DMA_0_S2MM_BURST_SIZE 0x10
#define XPAR_AXI_DMA_0_MICRO_DMA 0x0
#define XPAR_AXI_DMA_0_ADDRWIDTH 0x20
#define XPAR_AXI_DMA_0_SG_LENGTH_WIDTH 0x10

/* Canonical definitions for peripheral AXI_DMA_0 */
#define XPAR_XAXIDMA_0_BASEADDR 0x41e00000
#define XPAR_XAXIDMA_0_HIGHADDR 0x41e0ffff
#define XPAR_XAXIDMA_0_ADDRWIDTH 0x20
#define XPAR_XAXIDMA_0_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_XAXIDMA_0_INCLUDE_MM2S 0x0
#define XPAR_XAXIDMA_0_INCLUDE_MM2S_DRE 0x0
#define XPAR_XAXIDMA_0_INCLUDE_S2MM 0x1
#define XPAR_XAXIDMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIDMA_0_MM2S_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_MM2S_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_MICRO_DMA 0x0
#define XPAR_XAXIDMA_0_NUM_MM2S_CHANNELS 0x1
#define XPAR_XAXIDMA_0_NUM_S2MM_CHANNELS 0x1
#define XPAR_XAXIDMA_0_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_XAXIDMA_0_S2MM_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_S2MM_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_SG_LENGTH_WIDTH 0x10

#define XPAR_XBRAM_NUM_INSTANCES 2

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_AXI_BRAM_CTRL_0_BASEADDR 0xc0000000
#define XPAR_AXI_BRAM_CTRL_0_HIGHADDR 0xc0001fff
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 0x20
#define XPAR_AXI_BRAM_CTRL_0_ECC 0x0
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0x0
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0x0

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_XBRAM_0_BASEADDR 0xc0000000
#define XPAR_XBRAM_0_HIGHADDR 0xc0001fff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_XBRAM_0_FAULT_INJECT 0x0

/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0xffff
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_1_BASEADDR 0x0
#define XPAR_XBRAM_1_HIGHADDR 0xffff
#define XPAR_XBRAM_1_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_1_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_1_DATA_WIDTH 0x20
#define XPAR_XBRAM_1_ECC 0x0
#define XPAR_XBRAM_1_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_1_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_1_FAULT_INJECT 0x0
#define XPAR_XBRAM_1_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_1_WRITE_ACCESS 0x2

#define XPAR_XGPIO_NUM_INSTANCES 12

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_0_IS_DUAL 0x1
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x10
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_1_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_1_IS_DUAL 0x1
#define XPAR_AXI_GPIO_1_GPIO_WIDTH 0x2

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x2
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_10 */
#define XPAR_AXI_GPIO_10_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_10_BASEADDR 0x400b0000
#define XPAR_AXI_GPIO_10_HIGHADDR 0x400bffff
#define XPAR_AXI_GPIO_10_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_10_IS_DUAL 0x0
#define XPAR_AXI_GPIO_10_INTERRUPTS 0x2005
#define XPAR_FABRIC_AXI_GPIO_10_INTR 5
#define XPAR_AXI_GPIO_10_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_10_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_GPIO_10 */
#define XPAR_XGPIO_2_BASEADDR 0x400b0000
#define XPAR_FABRIC_XGPIO_2_INTR 5
#define XPAR_XGPIO_2_HIGHADDR 0x400bffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x1
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_2_IS_DUAL 0x0
#define XPAR_XGPIO_2_INTERRUPTS 0x2005
#define XPAR_XGPIO_2_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_2 */
#define XPAR_AXI_GPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_2_BASEADDR 0x40020000
#define XPAR_AXI_GPIO_2_HIGHADDR 0x4002ffff
#define XPAR_AXI_GPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_2_IS_DUAL 0x1
#define XPAR_AXI_GPIO_2_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_2 */
#define XPAR_XGPIO_3_BASEADDR 0x40020000
#define XPAR_XGPIO_3_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x10
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_3 */
#define XPAR_AXI_GPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_3_BASEADDR 0x40040000
#define XPAR_AXI_GPIO_3_HIGHADDR 0x4004ffff
#define XPAR_AXI_GPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_3_IS_DUAL 0x1
#define XPAR_AXI_GPIO_3_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_3 */
#define XPAR_XGPIO_4_BASEADDR 0x40040000
#define XPAR_XGPIO_4_HIGHADDR 0x4004ffff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x10
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_4_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_4 */
#define XPAR_AXI_GPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_4_BASEADDR 0x40050000
#define XPAR_AXI_GPIO_4_HIGHADDR 0x4005ffff
#define XPAR_AXI_GPIO_4_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_4_IS_DUAL 0x1
#define XPAR_AXI_GPIO_4_INTERRUPTS 0x2002
#define XPAR_FABRIC_AXI_GPIO_4_INTR 2
#define XPAR_AXI_GPIO_4_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_4_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_GPIO_4 */
#define XPAR_XGPIO_5_BASEADDR 0x40050000
#define XPAR_FABRIC_XGPIO_5_INTR 2
#define XPAR_XGPIO_5_HIGHADDR 0x4005ffff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0x1
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_5_IS_DUAL 0x1
#define XPAR_XGPIO_5_INTERRUPTS 0x2002
#define XPAR_XGPIO_5_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_5 */
#define XPAR_AXI_GPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_5_BASEADDR 0x40060000
#define XPAR_AXI_GPIO_5_HIGHADDR 0x4006ffff
#define XPAR_AXI_GPIO_5_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_5_IS_DUAL 0x1
#define XPAR_AXI_GPIO_5_INTERRUPTS 0x2003
#define XPAR_FABRIC_AXI_GPIO_5_INTR 3
#define XPAR_AXI_GPIO_5_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_5_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_GPIO_5 */
#define XPAR_XGPIO_6_BASEADDR 0x40060000
#define XPAR_FABRIC_XGPIO_6_INTR 3
#define XPAR_XGPIO_6_HIGHADDR 0x4006ffff
#define XPAR_XGPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_6_GPIO_WIDTH 0x1
#define XPAR_XGPIO_6_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_6_IS_DUAL 0x1
#define XPAR_XGPIO_6_INTERRUPTS 0x2003
#define XPAR_XGPIO_6_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_6 */
#define XPAR_AXI_GPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_6_BASEADDR 0x40070000
#define XPAR_AXI_GPIO_6_HIGHADDR 0x4007ffff
#define XPAR_AXI_GPIO_6_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_6_IS_DUAL 0x1
#define XPAR_AXI_GPIO_6_INTERRUPTS 0x2004
#define XPAR_FABRIC_AXI_GPIO_6_INTR 4
#define XPAR_AXI_GPIO_6_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_6_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_GPIO_6 */
#define XPAR_XGPIO_7_BASEADDR 0x40070000
#define XPAR_FABRIC_XGPIO_7_INTR 4
#define XPAR_XGPIO_7_HIGHADDR 0x4007ffff
#define XPAR_XGPIO_7_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_7_GPIO_WIDTH 0x1
#define XPAR_XGPIO_7_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_7_IS_DUAL 0x1
#define XPAR_XGPIO_7_INTERRUPTS 0x2004
#define XPAR_XGPIO_7_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_7 */
#define XPAR_AXI_GPIO_7_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_7_BASEADDR 0x40080000
#define XPAR_AXI_GPIO_7_HIGHADDR 0x4008ffff
#define XPAR_AXI_GPIO_7_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_7_IS_DUAL 0x1
#define XPAR_AXI_GPIO_7_GPIO_WIDTH 0x3

/* Canonical definitions for peripheral AXI_GPIO_7 */
#define XPAR_XGPIO_8_BASEADDR 0x40080000
#define XPAR_XGPIO_8_HIGHADDR 0x4008ffff
#define XPAR_XGPIO_8_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_8_GPIO_WIDTH 0x3
#define XPAR_XGPIO_8_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_8_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_8 */
#define XPAR_AXI_GPIO_8_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_8_BASEADDR 0x40090000
#define XPAR_AXI_GPIO_8_HIGHADDR 0x4009ffff
#define XPAR_AXI_GPIO_8_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_8_IS_DUAL 0x1
#define XPAR_AXI_GPIO_8_GPIO_WIDTH 0x2

/* Canonical definitions for peripheral AXI_GPIO_8 */
#define XPAR_XGPIO_9_BASEADDR 0x40090000
#define XPAR_XGPIO_9_HIGHADDR 0x4009ffff
#define XPAR_XGPIO_9_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_9_GPIO_WIDTH 0x2
#define XPAR_XGPIO_9_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_9_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_9 */
#define XPAR_AXI_GPIO_9_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_9_BASEADDR 0x400a0000
#define XPAR_AXI_GPIO_9_HIGHADDR 0x400affff
#define XPAR_AXI_GPIO_9_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_9_IS_DUAL 0x0
#define XPAR_AXI_GPIO_9_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_9 */
#define XPAR_XGPIO_10_BASEADDR 0x400a0000
#define XPAR_XGPIO_10_HIGHADDR 0x400affff
#define XPAR_XGPIO_10_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_10_GPIO_WIDTH 0x4
#define XPAR_XGPIO_10_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_10_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_IRQ_SPI */
#define XPAR_AXI_GPIO_IRQ_SPI_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_IRQ_SPI_BASEADDR 0x40030000
#define XPAR_AXI_GPIO_IRQ_SPI_HIGHADDR 0x4003ffff
#define XPAR_AXI_GPIO_IRQ_SPI_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_IRQ_SPI_IS_DUAL 0x0
#define XPAR_AXI_GPIO_IRQ_SPI_INTERRUPTS 0x2001
#define XPAR_FABRIC_AXI_GPIO_IRQ_SPI_INTR 1
#define XPAR_AXI_GPIO_IRQ_SPI_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_IRQ_SPI_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral AXI_GPIO_IRQ_SPI */
#define XPAR_XGPIO_11_BASEADDR 0x40030000
#define XPAR_FABRIC_XGPIO_11_INTR 1
#define XPAR_XGPIO_11_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_11_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_11_GPIO_WIDTH 0x1
#define XPAR_XGPIO_11_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_11_IS_DUAL 0x0
#define XPAR_XGPIO_11_INTERRUPTS 0x2001
#define XPAR_XGPIO_11_INTERRUPT_PARENT 0x41200001

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x6
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_SW_INTR 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_IVR 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_CIE 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_SIE 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_IPR 0x1

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x1
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x6
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XSYSMON_NUM_INSTANCES 1

/* Definitions for peripheral XADC_WIZ_0 */
#define XPAR_XADC_WIZ_0_COMPATIBLE "xlnx,xadc-wiz-3.3"
#define XPAR_XADC_WIZ_0_BASEADDR 0x44a00000
#define XPAR_XADC_WIZ_0_HIGHADDR 0x44a0ffff
#define XPAR_XADC_WIZ_0_INCLUDE_INTR 0x1
#define XPAR_XADC_WIZ_0_IP_TYPE 0x0

/* Canonical definitions for peripheral XADC_WIZ_0 */
#define XPAR_XSYSMON_0_BASEADDR 0x44a00000
#define XPAR_XSYSMON_0_HIGHADDR 0x44a0ffff
#define XPAR_XSYSMON_0_COMPATIBLE "xlnx,xadc-wiz-3.3"
#define XPAR_XSYSMON_0_INCLUDE_INTR 0x1
#define XPAR_XSYSMON_0_IP_TYPE 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x0
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 0
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_0_INTR 0
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x0
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/*  BOARD definition */
#define XPS_BOARD_CMOD_A7-35T

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff
#define XPAR_AXI_BRAM_0_BASEADDRESS 0xc0000000
#define XPAR_AXI_BRAM_0_HIGHADDRESS 0xc0001fff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_EXCEPTIONS_IN_DELAY_SLOTS 1
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_I_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_I_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 0
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 0
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER2 0
#define XPAR_MICROBLAZE_RESET_MSR 0
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_I_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_I_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_REG 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_DDR_RESERVE_SA 0

#define XPAR_MICROBLAZE_ADDR_SIZE 32

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a35t"

#endif  /* end of protection macro */